<img src="https://img.shields.io/badge/license-MIT-blue.svg" alt="License: MIT" />
<img src="https://img.shields.io/npm/v/@ddes/core.svg" alt="NPM version" />
<img src="https://img.shields.io/badge/node->= 8.10-blue.svg" alt="Node compatibility" />
<img src="https://img.shields.io/npm/types/@ddes/core.svg" alt="Type definitions" />
<img src="https://travis-ci.org/Skalar/ddes.svg?branch=master" alt="Build status" />

<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
